# Generated by Django 2.2.4 on 2019-09-02 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custumuser',
            options={'ordering': ('id',)},
        ),
    ]
